### ISSUE TITLE
Not redirecting to PayU

### ISSUE THREAD

**Issue by jrusi** [PayU/plugin_opencart_2#1]
On the tab "Order confirmation" when the button "Place teraz z PayU ->" is clicked nothing happens. 

Access log shows: 
"GET /index.php?route=payment/payu/pay&amp;_=1444859088327 HTTP/1.0
Status: 500 20 B"
No errors in Error log. 

All required parameters configured in admin.
curl and hash enabled

Opencart 2.1.0.1

**Comment by regdos** [comment]
Please install new release with FIX - https://github.com/PayU/plugin_opencart_2/releases/tag/3.0.1

**Comment by jrusi** [comment]
After installing new release 3.0.1 plugin works only on http connection. When using https Firefox is blocking the redirect to PayU with this message: 
"Firefox is blocking content on this page. Most websites will work properly even if content is blocked. Insecure content.
Some unencrypted elements on this website have been blocked"

**Comment by regdos** [comment]
In opencart config.php file set https protocol in HTTP_SERVER
eg. define('HTTP_SERVER', 'https://xxx.yyy/');

**Comment by jrusi** [comment]
Works perfectly! Thx a lot.
