### ISSUE TITLE
Does not show Extension in version 2.3.0

### ISSUE THREAD

**Issue by rakeshtembhurne** [PayU/plugin_opencart_2#2]
Followed Instructions given in Installation part, uploaded all files, but it does not show 'PayU' in extensions. It neither increase count of payment extensions (47 earlier).

**Comment by lukasz-grzesiak-payu-gpo** [comment]
Hi! Before we'll take a look into this issue, could you pls confirm that you have OpenCart 2.0.3 (you provided 2.3.0, was it a typo?) and that you want to integrate payments via PayU S.A. (this PayU branch has payment license for the EU, but not for India, Latin America or South Africa).
