### ISSUE TITLE
Currency Error

### ISSUE THREAD

**Issue by ahmetozcan9211** [PayU/plugin_opencart_2#7]
i cant use this plugin with my currency. my currency is TRY (turkish Lira) help me pls

**Comment by lukasz-grzesiak-payu-gpo** [comment]
Hi, this plugin is for PayU S.A. which is headquartered in Poland and services the European Union (Czech Rep. Hungary, Poland, Romania etc.). You probably want to integrate with PayU Turkey. Please contact the Turkish PayU directly: help@payu.com.tr
